# config/dev.exs

import Config

# Configuração do banco de dados Ecto para SQLite3
# --- ADICIONE ESTE BLOCO AQUI ---
config :cadence_backend, CadenceBackend.Repo,
  adapter: Ecto.Adapters.SQLite3, # <--- Adaptador para SQLite3
  database: "priv/repo/cadence_backend_dev.sqlite3", # <--- Caminho para o arquivo SQLite
  pool_size: 5 # Pool de conexão menor para SQLite
# --- FIM DO BLOCO ADICIONADO ---


# For development, we disable any cache and enable
# debugging and code reloading.
config :cadence_backend, CadenceBackendWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "4ibFW/YVcw04YjlQRfymueQwbOvF8/BHhrX6mPE0xhRpQ21eWs93ET2S/B4Ft9yU",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :cadence_backend, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
